version: '2.3'

services:
    api:
        build: .
        restart: unless-stopped
        ports: 
            - 7474:7474
        environment:
            REDIS_CONNECTION: redis://:29e282d2-ee7d-4596-8c9d-40ec826d1890@forks.sandlabs.ru:6379/0
            SERVER_IP: 0.0.0.0
            SERVER_PORT: 7474
